"""Add mobile field to Rider class

Revision ID: c483da97a658
Revises: db45479e2ed7
Create Date: 2020-11-05 18:43:34.120246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c483da97a658'
down_revision = 'db45479e2ed7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('riders', sa.Column('mobile_numbe', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_riders_mobile_numbe'), 'riders', ['mobile_numbe'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_riders_mobile_numbe'), table_name='riders')
    op.drop_column('riders', 'mobile_numbe')
    op.alter_column('bookings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
